M48
; DRILL file {KiCad 6.0.0} date Tue 04 Jan 2022 02:05:42 EET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-01-04T02:05:42+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.152
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
%
G90
G05
T1
X80.645Y-117.945
X123.444Y-83.655
T2
X93.5Y-111.27
X123.5Y-111.27
T3
X79.375Y-123.025
X123.025Y-79.375
X123.025Y-123.025
T0
M30
